function [fitresult, gof] = createFit_2D(X, Y, Z)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2017 16:35:00


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Z );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
% figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
% subplot( 2, 1, 1 );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'Z vs. X, Y', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'X' );
% ylabel( 'Y' );
% zlabel( 'Z' );
% grid on
% view( 0.5, 90.0 );

% Make contour plot.
% subplot( 2, 1, 2 );
plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
% legend( h, 'untitled fit 1', 'Z vs. X, Y', 'Location', 'NorthEast' );
% Label axes
xlabel( 'X' );
ylabel( 'Y' );
grid on

%caxis([20 200])
