function [fitresult, gof] = createFit_exp_p2p(mean_x, meanFit)
%CREATEFIT(MEAN_X,MEANFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : mean_x
%      Y Output: meanFit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Feb-2018 14:08:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( mean_x, meanFit );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [137.814906793541 -0.701406143127289 69.2728634879366 -0.034953613022574];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'meanFit vs. mean_x', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel mean_x
% ylabel meanFit
% grid on


